name: CI Pipeline with Security Testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js environment (assuming you're using Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # specify your Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

  zapScan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Run OWASP ZAP Docker scan (without login)
      - name: Run OWASP ZAP scan
        run: |
          # Start the Node.js application in the background
          nohup npm start &

          # Wait for the application to be up and running
          echo "Waiting for the application to start..."
          sleep 10

          # Check if the application is responding
          curl --silent --fail http://localhost:3000 || exit 1

          # Run OWASP ZAP scan against the running application
          echo "Running OWASP ZAP scan..."
          docker run --rm -t owasp/zap2docker zap-baseline.py -t http://localhost:3000

          # Sleep for a few seconds to allow ZAP to complete the scan
          sleep 30

      # Upload the ZAP report (optional)
      - name: Upload ZAP report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap-report.html

